### ISSUE TITLE
Some `Sigma.Windows.Hayabusa.Rule` rules does not detect logs

### ISSUE THREAD

**Issue by fukusuket** [Velocidex/velociraptor-sigma-rules#24]
Hello :) 
I am trying `Sigma.Windows.Hayabusa.Rules` on `0.72 RC1` and some rules were not working, so I would like to report.(I noticed this when I was comparing the results with `Exchange.Windows.EventLogs.Hayabusa`)

Although I have only confirmed this on medium level or higher, the following rules did not detect logs in `Sigma.Windows.Hayabusa.Rules`.
- [Defender Alert (High)](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml#L5)
- [A Rule Has Been Deleted From The Windows Firewall Exception List](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/firewall_as/win_firewall_as_delete_rule.yml#L1)
- ~[MSI Installation From Suspicious Locations](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml)~ ... Maybe this can be resolved by using the latest rule?
- ~[Suspicious Non PowerShell WSMAN COM Provider](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/powershell/powershell_classic/posh_pc_wsman_com_provider_no_powershell.yml#L4)~ ... Maybe this can be resolved by using the latest rule?
- ~[Uncommon AppX Package Locations](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/appxdeployment_server/win_appxdeployment_server_uncommon_package_locations.yml)~... Maybe this can be resolved by using the latest rule?

Thank you for your time.

**Comment by fukusuket** [comment]
### Defender Alert (High)
#### sigma_rules.yaml
```yaml
title: Defender Alert (High)
logsource:
  product: windows
  service: windefend
detection:
  condition: []
  selection:
    Channel: Microsoft-Windows-Windows Defender/Operational
    EventID: 1116
    SeverityID: 4
status: test
author: Zach Mathis, Fukusuke Takahashi
level: high
references:
  - https://github.com/Yamato-Security/hayabusa-rules/tree/main/hayabusa/hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml
```

#### Hayabusa original
```yaml
author: Zach Mathis, Fukusuke Takahashi
date: 2021/12/01
modified: 2023/6/17

title: 'Defender Alert (High)'
description: Windows defender malware detection

id: 1e11c0f0-aecd-45d8-9229-da679c0265ea
level: high
status: test
logsource:
    product: windows
    service: windefend
detection:
    selection:
        Channel: Microsoft-Windows-Windows Defender/Operational
        EventID: 1116
        SeverityID: 4 # High
falsepositives:
    - bad signature
tags:
    - malware
references:
    - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide
ruletype: Hayabusa
```

**Comment by fukusuket** [comment]
### A Rule Has Been Deleted From The Windows Firewall Exception List
#### sigma_rules.yaml
```yaml
title: A Rule Has Been Deleted From The Windows Firewall Exception List
logsource:
  product: windows
  service: firewall-as
detection:
  condition: (firewall_as and (selection and not 1 of filter_main_* and not 1 of filter_optional_*))
  filter_main_empty:
    ModifyingApplication: ""
  filter_main_generic:
    ModifyingApplication|startswith:
      - C:\Program Files\
      - C:\Program Files (x86)\
  filter_main_null:
    ModifyingApplication: null
  filter_main_svchost:
    ModifyingApplication: C:\Windows\System32\svchost.exe
  filter_optional_msmpeng:
    ModifyingApplication|startswith: C:\ProgramData\Microsoft\Windows Defender\Platform\
    ModifyingApplication|endswith: \MsMpEng.exe
  firewall_as:
    Channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
  selection:
    EventID:
      - 2006
      - 2052
status: experimental
author: frack113
level: medium
references:
  - https://github.com/Yamato-Security/hayabusa-rules/tree/main/hayabusa/sigma/builtin/firewall_as/win_firewall_as_delete_rule.yml
```

#### [Hayabusa original](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/firewall_as/win_firewall_as_delete_rule.yml)
```yaml
title: A Rule Has Been Deleted From The Windows Firewall Exception List
id: c187c075-bb3e-4c62-b4fa-beae0ffc211f
status: experimental
description: Detects when a single rules or all of the rules have been deleted from the Windows Defender Firewall
references:
    - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
author: frack113
date: 2022/02/19
modified: 2023/06/12
tags:
    - attack.defense_evasion
    - attack.t1562.004
logsource:
    product: windows
    service: firewall-as
detection:
    firewall_as:
        Channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    selection:
        EventID:
            - 2006 # A rule has been deleted in the Windows Defender Firewall exception list
            - 2052 # A rule has been deleted in the Windows Defender Firewall exception list. (Windows 11)
    filter_main_generic:
        ModifyingApplication|startswith:
            - C:\Program Files\
            - C:\Program Files (x86)\
    filter_main_svchost:
        ModifyingApplication: C:\Windows\System32\svchost.exe
    filter_optional_msmpeng:
        ModifyingApplication|startswith: C:\ProgramData\Microsoft\Windows Defender\Platform\
        ModifyingApplication|endswith: \MsMpEng.exe
    filter_main_null:
        ModifyingApplication:
    filter_main_empty:
        ModifyingApplication: ''
    condition: firewall_as and (selection and not 1 of filter_main_* and not 1 of filter_optional_*)
level: medium
ruletype: Sigma
```

**Comment by fukusuket** [comment]
### MSI Installation From Suspicious Locations
#### sigma_rules.yaml
```yaml
title: MSI Installation From Suspicious Locations
logsource:
  product: windows
  service: application
detection:
  condition: (application and (selection and not 1 of filter_*))
  application:
    Channel: Application
  filter_updhealthtools:
    Data|contains: C:\Windows\TEMP\UpdHealthTools.msi
  filter_winget:
    Data|contains: \AppData\Local\Temp\WinGet\
  selection:
    Provider_Name: MsiInstaller
    EventID:
      - 1040
      - 1042
    Data|contains:
      - \Users\Public\
      - \PerfLogs\
      - \Desktop\
      - C:\Windows\TEMP\
      - \\\\
status: experimental
author: Nasreddine Bencherchali (Nextron Systems)
level: medium
references:
  - https://github.com/Yamato-Security/hayabusa-rules/tree/main/hayabusa/sigma/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml
```

#### [Hayabusa original](https://github.com/Yamato-Security/hayabusa-rules/blob/066186d7119b0d16725563aa1c7c148dcbc6717a/sigma/builtin/application/msiinstaller/win_msi_install_from_susp_locations.yml)
```yaml
title: MSI Installation From Suspicious Locations
id: c7c8aa1c-5aff-408e-828b-998e3620b341
status: test
description: Detects MSI package installation from suspicious locations
references:
    - https://www.trendmicro.com/en_us/research/22/h/ransomware-actor-abuses-genshin-impact-anti-cheat-driver-to-kill-antivirus.html
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/08/31
modified: 2023/10/23
tags:
    - attack.execution
logsource:
    product: windows
    service: application
    # warning: The 'data' field used in the detection section is the container for the event data as a whole. You may have to adapt the rule for your backend accordingly
detection:
    application:
        Channel: Application
    selection:
        Provider_Name: MsiInstaller
        EventID:
            - 1040
            - 1042
        Data|contains:
            # Add more suspicious paths
            - :\Windows\TEMP\
            - \\\\
            - \Desktop\
            - \PerfLogs\
            - \Users\Public\
            # - '\AppData\Local\Temp\'  # too many FPs
            # - '\Downloads\'  # too many FPs, typical legitimate staging directory
    filter_winget:
        Data|contains: \AppData\Local\Temp\WinGet\
    filter_updhealthtools:
        Data|contains: C:\Windows\TEMP\UpdHealthTools.msi
    condition: application and (selection and not 1 of filter_*)
falsepositives:
    - False positives may occur if you allow installation from folders such as the desktop, the public folder or remote shares. A baseline is required before production use.
level: medium
ruletype: Sigma
```
